name: laplace
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - opt_einsum
  - matplotlib       # <— added
  - pyparsing        # <— added to satisfy matplotlib
  - pip:
    - asdfghjkl==0.1a4
    - backpack-for-pytorch
    - curvlinops-for-pytorch>=2.0
    - torch>=2.0
    - torchvision>=0.15
    - torchmetrics
    - -e .
